'use client';

import { Sparkles, ArrowRight } from 'lucide-react';
import SpotlightCard from '@/components/ui/SpotlightCard';

export default function BillNarrativeCard({ report }) {
  if (!report || !report.narrativeSummary) return null;

  return (
    <SpotlightCard className="p-8 bg-gradient-to-br from-cyan-950/40 to-surface-1000/20 backdrop-blur-md border-cyan-500/20 relative overflow-hidden h-full flex flex-col">
      <div className="absolute top-0 right-0 w-64 h-64 bg-cyan-500/10 blur-[80px] rounded-full -translate-y-1/2 translate-x-1/2" />
      
      <div className="flex items-center gap-4 mb-6 relative z-10">
        <div className="w-12 h-12 rounded-2xl bg-cyan-500/20 border border-cyan-500/30 flex items-center justify-center shadow-[0_0_15px_rgba(6,182,212,0.3)]">
          <Sparkles className="w-6 h-6 text-cyan-400" />
        </div>
        <div>
          <h3 className="text-xl font-bold text-white">AI Bill Analysis</h3>
          <p className="text-[10px] text-cyan-400/80 font-bold uppercase tracking-widest mt-1">Generated by OptiCore</p>
        </div>
      </div>

      <div className="relative z-10 flex-1">
        <p className="text-sm text-slate-300 leading-relaxed font-medium">
          {report.narrativeSummary}
        </p>
      </div>

      {report.potentialSavings && (
        <div className="mt-6 pt-6 border-t border-white/5 flex items-center justify-between relative z-10">
          <div>
            <p className="text-[10px] text-slate-400 uppercase font-black tracking-widest mb-1">Potential Optimization</p>
            <p className="text-xl font-black text-cyan-400 tabular-nums">{report.potentialSavings}</p>
          </div>
          <button className="w-10 h-10 rounded-xl bg-white/[0.05] hover:bg-cyan-500/20 border border-white/10 hover:border-cyan-500/30 flex items-center justify-center transition-colors group">
            <ArrowRight className="w-4 h-4 text-slate-400 group-hover:text-cyan-400 transition-colors" />
          </button>
        </div>
      )}
    </SpotlightCard>
  );
}
